// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// The API key
func GetApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "tailscale-native:apiKey")
}

// The OAuth client ID
func GetClientId(ctx *pulumi.Context) string {
	return config.Get(ctx, "tailscale-native:clientId")
}

// The OAuth client secret
func GetClientSecret(ctx *pulumi.Context) string {
	return config.Get(ctx, "tailscale-native:clientSecret")
}
