# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities
from ._enums import *

__all__ = [
    'AclRuleArgs',
    'NodeAttrsArgs',
    'SshRuleArgs',
]

@pulumi.input_type
class AclRuleArgs:
    def __init__(__self__, *,
                 action: pulumi.Input['AclRuleAction'],
                 ports: pulumi.Input[Sequence[pulumi.Input[str]]],
                 users: pulumi.Input[Sequence[pulumi.Input[str]]]):
        pulumi.set(__self__, "action", action)
        pulumi.set(__self__, "ports", ports)
        pulumi.set(__self__, "users", users)

    @property
    @pulumi.getter
    def action(self) -> pulumi.Input['AclRuleAction']:
        return pulumi.get(self, "action")

    @action.setter
    def action(self, value: pulumi.Input['AclRuleAction']):
        pulumi.set(self, "action", value)

    @property
    @pulumi.getter
    def ports(self) -> pulumi.Input[Sequence[pulumi.Input[str]]]:
        return pulumi.get(self, "ports")

    @ports.setter
    def ports(self, value: pulumi.Input[Sequence[pulumi.Input[str]]]):
        pulumi.set(self, "ports", value)

    @property
    @pulumi.getter
    def users(self) -> pulumi.Input[Sequence[pulumi.Input[str]]]:
        return pulumi.get(self, "users")

    @users.setter
    def users(self, value: pulumi.Input[Sequence[pulumi.Input[str]]]):
        pulumi.set(self, "users", value)


@pulumi.input_type
class NodeAttrsArgs:
    def __init__(__self__, *,
                 attr: pulumi.Input[Sequence[pulumi.Input[str]]],
                 target: pulumi.Input[Sequence[pulumi.Input[str]]]):
        pulumi.set(__self__, "attr", attr)
        pulumi.set(__self__, "target", target)

    @property
    @pulumi.getter
    def attr(self) -> pulumi.Input[Sequence[pulumi.Input[str]]]:
        return pulumi.get(self, "attr")

    @attr.setter
    def attr(self, value: pulumi.Input[Sequence[pulumi.Input[str]]]):
        pulumi.set(self, "attr", value)

    @property
    @pulumi.getter
    def target(self) -> pulumi.Input[Sequence[pulumi.Input[str]]]:
        return pulumi.get(self, "target")

    @target.setter
    def target(self, value: pulumi.Input[Sequence[pulumi.Input[str]]]):
        pulumi.set(self, "target", value)


@pulumi.input_type
class SshRuleArgs:
    def __init__(__self__, *,
                 action: pulumi.Input['SshRuleAction'],
                 check_period: pulumi.Input[str],
                 dst: pulumi.Input[Sequence[pulumi.Input[str]]],
                 src: pulumi.Input[Sequence[pulumi.Input[str]]],
                 users: pulumi.Input[Sequence[pulumi.Input[str]]]):
        pulumi.set(__self__, "action", action)
        pulumi.set(__self__, "check_period", check_period)
        pulumi.set(__self__, "dst", dst)
        pulumi.set(__self__, "src", src)
        pulumi.set(__self__, "users", users)

    @property
    @pulumi.getter
    def action(self) -> pulumi.Input['SshRuleAction']:
        return pulumi.get(self, "action")

    @action.setter
    def action(self, value: pulumi.Input['SshRuleAction']):
        pulumi.set(self, "action", value)

    @property
    @pulumi.getter(name="checkPeriod")
    def check_period(self) -> pulumi.Input[str]:
        return pulumi.get(self, "check_period")

    @check_period.setter
    def check_period(self, value: pulumi.Input[str]):
        pulumi.set(self, "check_period", value)

    @property
    @pulumi.getter
    def dst(self) -> pulumi.Input[Sequence[pulumi.Input[str]]]:
        return pulumi.get(self, "dst")

    @dst.setter
    def dst(self, value: pulumi.Input[Sequence[pulumi.Input[str]]]):
        pulumi.set(self, "dst", value)

    @property
    @pulumi.getter
    def src(self) -> pulumi.Input[Sequence[pulumi.Input[str]]]:
        return pulumi.get(self, "src")

    @src.setter
    def src(self, value: pulumi.Input[Sequence[pulumi.Input[str]]]):
        pulumi.set(self, "src", value)

    @property
    @pulumi.getter
    def users(self) -> pulumi.Input[Sequence[pulumi.Input[str]]]:
        return pulumi.get(self, "users")

    @users.setter
    def users(self, value: pulumi.Input[Sequence[pulumi.Input[str]]]):
        pulumi.set(self, "users", value)


