// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.TailscaleNative.Device
{
    [TailscaleNativeResourceType("tailscale-native:device:AuthorizeDevice")]
    public partial class AuthorizeDevice : global::Pulumi.CustomResource
    {
        [Output("authorized")]
        public Output<bool> Authorized { get; private set; } = null!;


        /// <summary>
        /// Create a AuthorizeDevice resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AuthorizeDevice(string name, AuthorizeDeviceArgs args, CustomResourceOptions? options = null)
            : base("tailscale-native:device:AuthorizeDevice", name, args ?? new AuthorizeDeviceArgs(), MakeResourceOptions(options, ""))
        {
        }

        private AuthorizeDevice(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("tailscale-native:device:AuthorizeDevice", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-tailscale-native",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AuthorizeDevice resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AuthorizeDevice Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new AuthorizeDevice(name, id, options);
        }
    }

    public sealed class AuthorizeDeviceArgs : global::Pulumi.ResourceArgs
    {
        [Input("authorized", required: true)]
        public Input<bool> Authorized { get; set; } = null!;

        [Input("id")]
        public Input<string>? Id { get; set; }

        public AuthorizeDeviceArgs()
        {
        }
        public static new AuthorizeDeviceArgs Empty => new AuthorizeDeviceArgs();
    }
}
