// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.TailscaleNative.Device
{
    public static class GetRoutesConfig
    {
        public static Task<Outputs.DeviceRoutes> InvokeAsync(GetRoutesConfigArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<Outputs.DeviceRoutes>("tailscale-native:device:getRoutesConfig", args ?? new GetRoutesConfigArgs(), options.WithDefaults());

        public static Output<Outputs.DeviceRoutes> Invoke(GetRoutesConfigInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<Outputs.DeviceRoutes>("tailscale-native:device:getRoutesConfig", args ?? new GetRoutesConfigInvokeArgs(), options.WithDefaults());

        public static Output<Outputs.DeviceRoutes> Invoke(GetRoutesConfigInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<Outputs.DeviceRoutes>("tailscale-native:device:getRoutesConfig", args ?? new GetRoutesConfigInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetRoutesConfigArgs : global::Pulumi.InvokeArgs
    {
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        public GetRoutesConfigArgs()
        {
        }
        public static new GetRoutesConfigArgs Empty => new GetRoutesConfigArgs();
    }

    public sealed class GetRoutesConfigInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public GetRoutesConfigInvokeArgs()
        {
        }
        public static new GetRoutesConfigInvokeArgs Empty => new GetRoutesConfigInvokeArgs();
    }
}
