// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.TailscaleNative.Device
{
    [TailscaleNativeResourceType("tailscale-native:device:RoutesConfig")]
    public partial class RoutesConfig : global::Pulumi.CustomResource
    {
        [Output("advertisedRoutes")]
        public Output<ImmutableArray<string>> AdvertisedRoutes { get; private set; } = null!;

        [Output("enabledRoutes")]
        public Output<ImmutableArray<string>> EnabledRoutes { get; private set; } = null!;

        [Output("routes")]
        public Output<ImmutableArray<string>> Routes { get; private set; } = null!;


        /// <summary>
        /// Create a RoutesConfig resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public RoutesConfig(string name, RoutesConfigArgs args, CustomResourceOptions? options = null)
            : base("tailscale-native:device:RoutesConfig", name, args ?? new RoutesConfigArgs(), MakeResourceOptions(options, ""))
        {
        }

        private RoutesConfig(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("tailscale-native:device:RoutesConfig", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-tailscale-native",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing RoutesConfig resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static RoutesConfig Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new RoutesConfig(name, id, options);
        }
    }

    public sealed class RoutesConfigArgs : global::Pulumi.ResourceArgs
    {
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("routes", required: true)]
        private InputList<string>? _routes;
        public InputList<string> Routes
        {
            get => _routes ?? (_routes = new InputList<string>());
            set => _routes = value;
        }

        public RoutesConfigArgs()
        {
        }
        public static new RoutesConfigArgs Empty => new RoutesConfigArgs();
    }
}
