// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.TailscaleNative.Device
{
    [TailscaleNativeResourceType("tailscale-native:device:Tags")]
    public partial class Tags : global::Pulumi.CustomResource
    {
        [Output("tags")]
        public Output<ImmutableArray<string>> TagsValue { get; private set; } = null!;


        /// <summary>
        /// Create a Tags resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Tags(string name, TagsArgs args, CustomResourceOptions? options = null)
            : base("tailscale-native:device:Tags", name, args ?? new TagsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Tags(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("tailscale-native:device:Tags", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-tailscale-native",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Tags resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Tags Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Tags(name, id, options);
        }
    }

    public sealed class TagsArgs : global::Pulumi.ResourceArgs
    {
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("tags", required: true)]
        private InputList<string>? _tags;
        public InputList<string> TagsValue
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        public TagsArgs()
        {
        }
        public static new TagsArgs Empty => new TagsArgs();
    }
}
