// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.TailscaleNative.Tailnet
{
    [TailscaleNativeResourceType("tailscale-native:tailnet:Acl")]
    public partial class Acl : global::Pulumi.CustomResource
    {
        [Output("acls")]
        public Output<ImmutableArray<Outputs.AclRule>> Acls { get; private set; } = null!;

        [Output("autoApprovers")]
        public Output<object> AutoApprovers { get; private set; } = null!;

        [Output("groups")]
        public Output<object> Groups { get; private set; } = null!;

        [Output("hosts")]
        public Output<object> Hosts { get; private set; } = null!;

        [Output("nodeAttrs")]
        public Output<ImmutableArray<Outputs.NodeAttrs>> NodeAttrs { get; private set; } = null!;

        [Output("ssh")]
        public Output<ImmutableArray<Outputs.SshRule>> Ssh { get; private set; } = null!;

        [Output("tagOwners")]
        public Output<object> TagOwners { get; private set; } = null!;

        [Output("tests")]
        public Output<string> Tests { get; private set; } = null!;


        /// <summary>
        /// Create a Acl resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Acl(string name, AclArgs args, CustomResourceOptions? options = null)
            : base("tailscale-native:tailnet:Acl", name, args ?? new AclArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Acl(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("tailscale-native:tailnet:Acl", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-tailscale",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Acl resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Acl Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Acl(name, id, options);
        }
    }

    public sealed class AclArgs : global::Pulumi.ResourceArgs
    {
        [Input("acls", required: true)]
        private InputList<Inputs.AclRuleArgs>? _acls;
        public InputList<Inputs.AclRuleArgs> Acls
        {
            get => _acls ?? (_acls = new InputList<Inputs.AclRuleArgs>());
            set => _acls = value;
        }

        [Input("autoApprovers", required: true)]
        public Input<object> AutoApprovers { get; set; } = null!;

        [Input("groups", required: true)]
        public Input<object> Groups { get; set; } = null!;

        [Input("hosts", required: true)]
        public Input<object> Hosts { get; set; } = null!;

        [Input("nodeAttrs", required: true)]
        private InputList<Inputs.NodeAttrsArgs>? _nodeAttrs;
        public InputList<Inputs.NodeAttrsArgs> NodeAttrs
        {
            get => _nodeAttrs ?? (_nodeAttrs = new InputList<Inputs.NodeAttrsArgs>());
            set => _nodeAttrs = value;
        }

        [Input("ssh", required: true)]
        private InputList<Inputs.SshRuleArgs>? _ssh;
        public InputList<Inputs.SshRuleArgs> Ssh
        {
            get => _ssh ?? (_ssh = new InputList<Inputs.SshRuleArgs>());
            set => _ssh = value;
        }

        [Input("tagOwners", required: true)]
        public Input<object> TagOwners { get; set; } = null!;

        [Input("tailnet")]
        public Input<string>? Tailnet { get; set; }

        [Input("tests", required: true)]
        public Input<string> Tests { get; set; } = null!;

        public AclArgs()
        {
        }
        public static new AclArgs Empty => new AclArgs();
    }
}
