// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.TailscaleNative.Tailnet
{
    [TailscaleNativeResourceType("tailscale-native:tailnet:DNSPreferences")]
    public partial class DNSPreferences : global::Pulumi.CustomResource
    {
        [Output("magicDNS")]
        public Output<bool> MagicDNS { get; private set; } = null!;


        /// <summary>
        /// Create a DNSPreferences resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DNSPreferences(string name, DNSPreferencesArgs args, CustomResourceOptions? options = null)
            : base("tailscale-native:tailnet:DNSPreferences", name, args ?? new DNSPreferencesArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DNSPreferences(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("tailscale-native:tailnet:DNSPreferences", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-tailscale-native",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DNSPreferences resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DNSPreferences Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new DNSPreferences(name, id, options);
        }
    }

    public sealed class DNSPreferencesArgs : global::Pulumi.ResourceArgs
    {
        [Input("magicDNS", required: true)]
        public Input<bool> MagicDNS { get; set; } = null!;

        [Input("tailnet")]
        public Input<string>? Tailnet { get; set; }

        public DNSPreferencesArgs()
        {
        }
        public static new DNSPreferencesArgs Empty => new DNSPreferencesArgs();
    }
}
