// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tailscale.Tailnet
{
    public static class GetAcl
    {
        public static Task<GetAclResult> InvokeAsync(GetAclArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAclResult>("tailscale:tailnet:getAcl", args ?? new GetAclArgs(), options.WithDefaults());

        public static Output<GetAclResult> Invoke(GetAclInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAclResult>("tailscale:tailnet:getAcl", args ?? new GetAclInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetAclArgs : global::Pulumi.InvokeArgs
    {
        [Input("tailnet", required: true)]
        public string Tailnet { get; set; } = null!;

        public GetAclArgs()
        {
        }
        public static new GetAclArgs Empty => new GetAclArgs();
    }

    public sealed class GetAclInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("tailnet", required: true)]
        public Input<string> Tailnet { get; set; } = null!;

        public GetAclInvokeArgs()
        {
        }
        public static new GetAclInvokeArgs Empty => new GetAclInvokeArgs();
    }


    [OutputType]
    public sealed class GetAclResult
    {
        public readonly Outputs.Acl Items;

        [OutputConstructor]
        private GetAclResult(Outputs.Acl items)
        {
            Items = items;
        }
    }
}
