// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.TailscaleNative.Tailnet
{
    public static class GetDNSPreferences
    {
        public static Task<GetDNSPreferencesResult> InvokeAsync(GetDNSPreferencesArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDNSPreferencesResult>("tailscale-native:tailnet:getDNSPreferences", args ?? new GetDNSPreferencesArgs(), options.WithDefaults());

        public static Output<GetDNSPreferencesResult> Invoke(GetDNSPreferencesInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDNSPreferencesResult>("tailscale-native:tailnet:getDNSPreferences", args ?? new GetDNSPreferencesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDNSPreferencesArgs : global::Pulumi.InvokeArgs
    {
        [Input("tailnet", required: true)]
        public string Tailnet { get; set; } = null!;

        public GetDNSPreferencesArgs()
        {
        }
        public static new GetDNSPreferencesArgs Empty => new GetDNSPreferencesArgs();
    }

    public sealed class GetDNSPreferencesInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("tailnet", required: true)]
        public Input<string> Tailnet { get; set; } = null!;

        public GetDNSPreferencesInvokeArgs()
        {
        }
        public static new GetDNSPreferencesInvokeArgs Empty => new GetDNSPreferencesInvokeArgs();
    }


    [OutputType]
    public sealed class GetDNSPreferencesResult
    {
        public readonly Outputs.NameServersPreference Items;

        [OutputConstructor]
        private GetDNSPreferencesResult(Outputs.NameServersPreference items)
        {
            Items = items;
        }
    }
}
