// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.TailscaleNative.Tailnet
{
    public static class ListDevices
    {
        public static Task<ListDevicesResult> InvokeAsync(ListDevicesArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<ListDevicesResult>("tailscale-native:tailnet:listDevices", args ?? new ListDevicesArgs(), options.WithDefaults());

        public static Output<ListDevicesResult> Invoke(ListDevicesInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<ListDevicesResult>("tailscale-native:tailnet:listDevices", args ?? new ListDevicesInvokeArgs(), options.WithDefaults());
    }


    public sealed class ListDevicesArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// For paid plans, your domain is your tailnet. For solo plans, the tailnet is the email you signed up with. So `alice@gmail.com` has the tailnet `alice@gmail.com` since `@gmail.com` is a shared email host. Alternatively, you can specify the value "-" to refer to the default tailnet of the authenticated user making the API call.
        /// </summary>
        [Input("tailnet", required: true)]
        public string Tailnet { get; set; } = null!;

        public ListDevicesArgs()
        {
        }
        public static new ListDevicesArgs Empty => new ListDevicesArgs();
    }

    public sealed class ListDevicesInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// For paid plans, your domain is your tailnet. For solo plans, the tailnet is the email you signed up with. So `alice@gmail.com` has the tailnet `alice@gmail.com` since `@gmail.com` is a shared email host. Alternatively, you can specify the value "-" to refer to the default tailnet of the authenticated user making the API call.
        /// </summary>
        [Input("tailnet", required: true)]
        public Input<string> Tailnet { get; set; } = null!;

        public ListDevicesInvokeArgs()
        {
        }
        public static new ListDevicesInvokeArgs Empty => new ListDevicesInvokeArgs();
    }


    [OutputType]
    public sealed class ListDevicesResult
    {
        public readonly Outputs.ListDevicesProperties Items;

        [OutputConstructor]
        private ListDevicesResult(Outputs.ListDevicesProperties items)
        {
            Items = items;
        }
    }
}
