// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tailscale.Tailnet
{
    [TailscaleResourceType("tailscale:tailnet:TailnetEndpoints_replaceSearchPaths")]
    public partial class TailnetEndpoints_replaceSearchPaths : global::Pulumi.CustomResource
    {
        [Output("searchPaths")]
        public Output<ImmutableArray<string>> SearchPaths { get; private set; } = null!;


        /// <summary>
        /// Create a TailnetEndpoints_replaceSearchPaths resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public TailnetEndpoints_replaceSearchPaths(string name, TailnetEndpoints_replaceSearchPathsArgs args, CustomResourceOptions? options = null)
            : base("tailscale:tailnet:TailnetEndpoints_replaceSearchPaths", name, args ?? new TailnetEndpoints_replaceSearchPathsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private TailnetEndpoints_replaceSearchPaths(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("tailscale:tailnet:TailnetEndpoints_replaceSearchPaths", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-tailscale",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing TailnetEndpoints_replaceSearchPaths resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static TailnetEndpoints_replaceSearchPaths Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new TailnetEndpoints_replaceSearchPaths(name, id, options);
        }
    }

    public sealed class TailnetEndpoints_replaceSearchPathsArgs : global::Pulumi.ResourceArgs
    {
        [Input("searchPaths", required: true)]
        private InputList<string>? _searchPaths;
        public InputList<string> SearchPaths
        {
            get => _searchPaths ?? (_searchPaths = new InputList<string>());
            set => _searchPaths = value;
        }

        [Input("tailnet")]
        public Input<string>? Tailnet { get; set; }

        public TailnetEndpoints_replaceSearchPathsArgs()
        {
        }
        public static new TailnetEndpoints_replaceSearchPathsArgs Empty => new TailnetEndpoints_replaceSearchPathsArgs();
    }
}
