// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const AclRuleAction = {
    Accept: "accept",
} as const;

/**
 * Tailscale ACL rules are "default deny".
 * So the only possible value for an ACL
 * rule is `accept`.
 */
export type AclRuleAction = (typeof AclRuleAction)[keyof typeof AclRuleAction];

export const SshRuleAction = {
    Check: "check",
    Accept: "accept",
} as const;

export type SshRuleAction = (typeof SshRuleAction)[keyof typeof SshRuleAction];
