// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package device

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type DeviceEndpoints_setKeyExpiry struct {
	pulumi.CustomResourceState

	KeyExpiryDisabled pulumi.BoolOutput `pulumi:"keyExpiryDisabled"`
}

// NewDeviceEndpoints_setKeyExpiry registers a new resource with the given unique name, arguments, and options.
func NewDeviceEndpoints_setKeyExpiry(ctx *pulumi.Context,
	name string, args *DeviceEndpoints_setKeyExpiryArgs, opts ...pulumi.ResourceOption) (*DeviceEndpoints_setKeyExpiry, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.KeyExpiryDisabled == nil {
		return nil, errors.New("invalid value for required argument 'KeyExpiryDisabled'")
	}
	opts = pkgResourceDefaultOpts(opts)
	var resource DeviceEndpoints_setKeyExpiry
	err := ctx.RegisterResource("tailscale:device:DeviceEndpoints_setKeyExpiry", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDeviceEndpoints_setKeyExpiry gets an existing DeviceEndpoints_setKeyExpiry resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDeviceEndpoints_setKeyExpiry(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DeviceEndpoints_setKeyExpiryState, opts ...pulumi.ResourceOption) (*DeviceEndpoints_setKeyExpiry, error) {
	var resource DeviceEndpoints_setKeyExpiry
	err := ctx.ReadResource("tailscale:device:DeviceEndpoints_setKeyExpiry", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DeviceEndpoints_setKeyExpiry resources.
type deviceEndpoints_setKeyExpiryState struct {
}

type DeviceEndpoints_setKeyExpiryState struct {
}

func (DeviceEndpoints_setKeyExpiryState) ElementType() reflect.Type {
	return reflect.TypeOf((*deviceEndpoints_setKeyExpiryState)(nil)).Elem()
}

type deviceEndpoints_setKeyExpiryArgs struct {
	Id                *string `pulumi:"id"`
	KeyExpiryDisabled bool    `pulumi:"keyExpiryDisabled"`
}

// The set of arguments for constructing a DeviceEndpoints_setKeyExpiry resource.
type DeviceEndpoints_setKeyExpiryArgs struct {
	Id                pulumi.StringPtrInput
	KeyExpiryDisabled pulumi.BoolInput
}

func (DeviceEndpoints_setKeyExpiryArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*deviceEndpoints_setKeyExpiryArgs)(nil)).Elem()
}

type DeviceEndpoints_setKeyExpiryInput interface {
	pulumi.Input

	ToDeviceEndpoints_setKeyExpiryOutput() DeviceEndpoints_setKeyExpiryOutput
	ToDeviceEndpoints_setKeyExpiryOutputWithContext(ctx context.Context) DeviceEndpoints_setKeyExpiryOutput
}

func (*DeviceEndpoints_setKeyExpiry) ElementType() reflect.Type {
	return reflect.TypeOf((**DeviceEndpoints_setKeyExpiry)(nil)).Elem()
}

func (i *DeviceEndpoints_setKeyExpiry) ToDeviceEndpoints_setKeyExpiryOutput() DeviceEndpoints_setKeyExpiryOutput {
	return i.ToDeviceEndpoints_setKeyExpiryOutputWithContext(context.Background())
}

func (i *DeviceEndpoints_setKeyExpiry) ToDeviceEndpoints_setKeyExpiryOutputWithContext(ctx context.Context) DeviceEndpoints_setKeyExpiryOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DeviceEndpoints_setKeyExpiryOutput)
}

type DeviceEndpoints_setKeyExpiryOutput struct{ *pulumi.OutputState }

func (DeviceEndpoints_setKeyExpiryOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DeviceEndpoints_setKeyExpiry)(nil)).Elem()
}

func (o DeviceEndpoints_setKeyExpiryOutput) ToDeviceEndpoints_setKeyExpiryOutput() DeviceEndpoints_setKeyExpiryOutput {
	return o
}

func (o DeviceEndpoints_setKeyExpiryOutput) ToDeviceEndpoints_setKeyExpiryOutputWithContext(ctx context.Context) DeviceEndpoints_setKeyExpiryOutput {
	return o
}

func (o DeviceEndpoints_setKeyExpiryOutput) KeyExpiryDisabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *DeviceEndpoints_setKeyExpiry) pulumi.BoolOutput { return v.KeyExpiryDisabled }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DeviceEndpoints_setKeyExpiryInput)(nil)).Elem(), &DeviceEndpoints_setKeyExpiry{})
	pulumi.RegisterOutputType(DeviceEndpoints_setKeyExpiryOutput{})
}
