// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package device

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type DeviceEndpoints_setTags struct {
	pulumi.CustomResourceState

	Tags pulumi.StringArrayOutput `pulumi:"tags"`
}

// NewDeviceEndpoints_setTags registers a new resource with the given unique name, arguments, and options.
func NewDeviceEndpoints_setTags(ctx *pulumi.Context,
	name string, args *DeviceEndpoints_setTagsArgs, opts ...pulumi.ResourceOption) (*DeviceEndpoints_setTags, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Tags == nil {
		return nil, errors.New("invalid value for required argument 'Tags'")
	}
	opts = pkgResourceDefaultOpts(opts)
	var resource DeviceEndpoints_setTags
	err := ctx.RegisterResource("tailscale:device:DeviceEndpoints_setTags", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDeviceEndpoints_setTags gets an existing DeviceEndpoints_setTags resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDeviceEndpoints_setTags(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DeviceEndpoints_setTagsState, opts ...pulumi.ResourceOption) (*DeviceEndpoints_setTags, error) {
	var resource DeviceEndpoints_setTags
	err := ctx.ReadResource("tailscale:device:DeviceEndpoints_setTags", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DeviceEndpoints_setTags resources.
type deviceEndpoints_setTagsState struct {
}

type DeviceEndpoints_setTagsState struct {
}

func (DeviceEndpoints_setTagsState) ElementType() reflect.Type {
	return reflect.TypeOf((*deviceEndpoints_setTagsState)(nil)).Elem()
}

type deviceEndpoints_setTagsArgs struct {
	Id   *string  `pulumi:"id"`
	Tags []string `pulumi:"tags"`
}

// The set of arguments for constructing a DeviceEndpoints_setTags resource.
type DeviceEndpoints_setTagsArgs struct {
	Id   pulumi.StringPtrInput
	Tags pulumi.StringArrayInput
}

func (DeviceEndpoints_setTagsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*deviceEndpoints_setTagsArgs)(nil)).Elem()
}

type DeviceEndpoints_setTagsInput interface {
	pulumi.Input

	ToDeviceEndpoints_setTagsOutput() DeviceEndpoints_setTagsOutput
	ToDeviceEndpoints_setTagsOutputWithContext(ctx context.Context) DeviceEndpoints_setTagsOutput
}

func (*DeviceEndpoints_setTags) ElementType() reflect.Type {
	return reflect.TypeOf((**DeviceEndpoints_setTags)(nil)).Elem()
}

func (i *DeviceEndpoints_setTags) ToDeviceEndpoints_setTagsOutput() DeviceEndpoints_setTagsOutput {
	return i.ToDeviceEndpoints_setTagsOutputWithContext(context.Background())
}

func (i *DeviceEndpoints_setTags) ToDeviceEndpoints_setTagsOutputWithContext(ctx context.Context) DeviceEndpoints_setTagsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DeviceEndpoints_setTagsOutput)
}

type DeviceEndpoints_setTagsOutput struct{ *pulumi.OutputState }

func (DeviceEndpoints_setTagsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DeviceEndpoints_setTags)(nil)).Elem()
}

func (o DeviceEndpoints_setTagsOutput) ToDeviceEndpoints_setTagsOutput() DeviceEndpoints_setTagsOutput {
	return o
}

func (o DeviceEndpoints_setTagsOutput) ToDeviceEndpoints_setTagsOutputWithContext(ctx context.Context) DeviceEndpoints_setTagsOutput {
	return o
}

func (o DeviceEndpoints_setTagsOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *DeviceEndpoints_setTags) pulumi.StringArrayOutput { return v.Tags }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DeviceEndpoints_setTagsInput)(nil)).Elem(), &DeviceEndpoints_setTags{})
	pulumi.RegisterOutputType(DeviceEndpoints_setTagsOutput{})
}
