// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package tailscale

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-tailscale-native/sdk/go/tailscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The provider type for the Tailscale package.
type Provider struct {
	pulumi.ProviderResourceState
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	if args.ApiKey == nil {
		if d := internal.GetEnvOrDefault(nil, nil, "TAILSCALE_NATIVE_APIKEY", "TAILSCALE_APIKEY"); d != nil {
			args.ApiKey = pulumi.StringPtr(d.(string))
		}
	}
	if args.ClientId == nil {
		if d := internal.GetEnvOrDefault(nil, nil, "TAILSCALE_NATIVE_CLIENT_ID", "TAILSCALE_CLIENT_ID"); d != nil {
			args.ClientId = pulumi.StringPtr(d.(string))
		}
	}
	if args.ClientSecret == nil {
		if d := internal.GetEnvOrDefault(nil, nil, "TAILSCALE_NATIVE_CLIENT_SECRET", "TAILSCALE_CLIENT_SECRET"); d != nil {
			args.ClientSecret = pulumi.StringPtr(d.(string))
		}
	}
	if args.ApiKey != nil {
		args.ApiKey = pulumi.ToSecret(args.ApiKey).(pulumi.StringPtrInput)
	}
	if args.ClientSecret != nil {
		args.ClientSecret = pulumi.ToSecret(args.ClientSecret).(pulumi.StringPtrInput)
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:tailscale-native", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// The Tailscale API key.
	ApiKey *string `pulumi:"apiKey"`
	// The Tailscale OAuth client ID.
	ClientId *string `pulumi:"clientId"`
	// The Tailscale OAuth client secret.
	ClientSecret *string `pulumi:"clientSecret"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// The Tailscale API key.
	ApiKey pulumi.StringPtrInput
	// The Tailscale OAuth client ID.
	ClientId pulumi.StringPtrInput
	// The Tailscale OAuth client secret.
	ClientSecret pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
