// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package tailnet

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-tailscale-native/sdk/go/tailscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNameServersConfig(ctx *pulumi.Context, args *LookupNameServersConfigArgs, opts ...pulumi.InvokeOption) (*LookupNameServersConfigResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupNameServersConfigResult
	err := ctx.Invoke("tailscale-native:tailnet:getNameServersConfig", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupNameServersConfigArgs struct {
	// For paid plans, your domain is your tailnet. For solo plans, the tailnet is the email you signed up with. So `alice@gmail.com` has the tailnet `alice@gmail.com` since `@gmail.com` is a shared email host. Alternatively, you can specify the value "-" to refer to the default tailnet of the authenticated user making the API call.
	Tailnet string `pulumi:"tailnet"`
}

type LookupNameServersConfigResult struct {
	Dns      []string `pulumi:"dns"`
	MagicDNS bool     `pulumi:"magicDNS"`
}

func LookupNameServersConfigOutput(ctx *pulumi.Context, args LookupNameServersConfigOutputArgs, opts ...pulumi.InvokeOption) LookupNameServersConfigResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupNameServersConfigResultOutput, error) {
			args := v.(LookupNameServersConfigArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("tailscale-native:tailnet:getNameServersConfig", args, LookupNameServersConfigResultOutput{}, options).(LookupNameServersConfigResultOutput), nil
		}).(LookupNameServersConfigResultOutput)
}

type LookupNameServersConfigOutputArgs struct {
	// For paid plans, your domain is your tailnet. For solo plans, the tailnet is the email you signed up with. So `alice@gmail.com` has the tailnet `alice@gmail.com` since `@gmail.com` is a shared email host. Alternatively, you can specify the value "-" to refer to the default tailnet of the authenticated user making the API call.
	Tailnet pulumi.StringInput `pulumi:"tailnet"`
}

func (LookupNameServersConfigOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNameServersConfigArgs)(nil)).Elem()
}

type LookupNameServersConfigResultOutput struct{ *pulumi.OutputState }

func (LookupNameServersConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNameServersConfigResult)(nil)).Elem()
}

func (o LookupNameServersConfigResultOutput) ToLookupNameServersConfigResultOutput() LookupNameServersConfigResultOutput {
	return o
}

func (o LookupNameServersConfigResultOutput) ToLookupNameServersConfigResultOutputWithContext(ctx context.Context) LookupNameServersConfigResultOutput {
	return o
}

func (o LookupNameServersConfigResultOutput) Dns() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupNameServersConfigResult) []string { return v.Dns }).(pulumi.StringArrayOutput)
}

func (o LookupNameServersConfigResultOutput) MagicDNS() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNameServersConfigResult) bool { return v.MagicDNS }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNameServersConfigResultOutput{})
}
