// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package tailnet

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-tailscale-native/sdk/go/tailscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNameServersConfig(ctx *pulumi.Context, args *LookupNameServersConfigArgs, opts ...pulumi.InvokeOption) (*LookupNameServersConfigResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupNameServersConfigResult
	err := ctx.Invoke("tailscale-native:tailnet:getNameServersConfig", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupNameServersConfigArgs struct {
	// For paid plans, your domain is your tailnet. For solo plans, the tailnet is the email you signed up with. So `alice@gmail.com` has the tailnet `alice@gmail.com` since `@gmail.com` is a shared email host. Alternatively, you can specify the value "-" to refer to the default tailnet of the authenticated user making the API call.
	Tailnet string `pulumi:"tailnet"`
}

type LookupNameServersConfigResult struct {
	Items NameServers `pulumi:"items"`
}

func LookupNameServersConfigOutput(ctx *pulumi.Context, args LookupNameServersConfigOutputArgs, opts ...pulumi.InvokeOption) LookupNameServersConfigResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupNameServersConfigResult, error) {
			args := v.(LookupNameServersConfigArgs)
			r, err := LookupNameServersConfig(ctx, &args, opts...)
			var s LookupNameServersConfigResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupNameServersConfigResultOutput)
}

type LookupNameServersConfigOutputArgs struct {
	// For paid plans, your domain is your tailnet. For solo plans, the tailnet is the email you signed up with. So `alice@gmail.com` has the tailnet `alice@gmail.com` since `@gmail.com` is a shared email host. Alternatively, you can specify the value "-" to refer to the default tailnet of the authenticated user making the API call.
	Tailnet pulumi.StringInput `pulumi:"tailnet"`
}

func (LookupNameServersConfigOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNameServersConfigArgs)(nil)).Elem()
}

type LookupNameServersConfigResultOutput struct{ *pulumi.OutputState }

func (LookupNameServersConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNameServersConfigResult)(nil)).Elem()
}

func (o LookupNameServersConfigResultOutput) ToLookupNameServersConfigResultOutput() LookupNameServersConfigResultOutput {
	return o
}

func (o LookupNameServersConfigResultOutput) ToLookupNameServersConfigResultOutputWithContext(ctx context.Context) LookupNameServersConfigResultOutput {
	return o
}

func (o LookupNameServersConfigResultOutput) Items() NameServersOutput {
	return o.ApplyT(func(v LookupNameServersConfigResult) NameServers { return v.Items }).(NameServersOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNameServersConfigResultOutput{})
}
