# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import pulumi
from enum import Enum

__all__ = [
    'AclRuleAction',
    'SshRuleAction',
]


@pulumi.type_token("tailscale-native:tailnet:AclRuleAction")
class AclRuleAction(builtins.str, Enum):
    """
    Tailscale ACL rules are "default deny".
    So the only possible value for an ACL
    rule is `accept`.
    """
    ACCEPT = "accept"


@pulumi.type_token("tailscale-native:tailnet:SshRuleAction")
class SshRuleAction(builtins.str, Enum):
    CHECK = "check"
    ACCEPT = "accept"
