# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities
from . import outputs

__all__ = [
    'ListSearchPathsResult',
    'AwaitableListSearchPathsResult',
    'list_search_paths',
    'list_search_paths_output',
]

@pulumi.output_type
class ListSearchPathsResult:
    def __init__(__self__, items=None):
        if items and not isinstance(items, dict):
            raise TypeError("Expected argument 'items' to be a dict")
        pulumi.set(__self__, "items", items)

    @property
    @pulumi.getter
    def items(self) -> 'outputs.DnsSearchPaths':
        return pulumi.get(self, "items")


class AwaitableListSearchPathsResult(ListSearchPathsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return ListSearchPathsResult(
            items=self.items)


def list_search_paths(tailnet: Optional[str] = None,
                      opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableListSearchPathsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['tailnet'] = tailnet
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('tailscale-native:tailnet:listSearchPaths', __args__, opts=opts, typ=ListSearchPathsResult).value

    return AwaitableListSearchPathsResult(
        items=__ret__.items)


@_utilities.lift_output_func(list_search_paths)
def list_search_paths_output(tailnet: Optional[pulumi.Input[str]] = None,
                             opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[ListSearchPathsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    ...
