# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload, Awaitable
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'DnsSearchPaths',
    'AwaitableDnsSearchPaths',
    'list_search_paths',
    'list_search_paths_output',
]

@pulumi.output_type
class DnsSearchPaths:
    def __init__(__self__, search_paths=None):
        if search_paths and not isinstance(search_paths, list):
            raise TypeError("Expected argument 'search_paths' to be a list")
        pulumi.set(__self__, "search_paths", search_paths)

    @property
    @pulumi.getter(name="searchPaths")
    def search_paths(self) -> Sequence[str]:
        return pulumi.get(self, "search_paths")


class AwaitableDnsSearchPaths(DnsSearchPaths):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return DnsSearchPaths(
            search_paths=self.search_paths)


def list_search_paths(tailnet: Optional[str] = None,
                      opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableDnsSearchPaths:
    """
    Use this data source to access information about an existing resource.

    :param str tailnet: For paid plans, your domain is your tailnet. For solo plans, the tailnet is the email you signed up with. So `alice@gmail.com` has the tailnet `alice@gmail.com` since `@gmail.com` is a shared email host. Alternatively, you can specify the value "-" to refer to the default tailnet of the authenticated user making the API call.
    """
    __args__ = dict()
    __args__['tailnet'] = tailnet
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('tailscale-native:tailnet:listSearchPaths', __args__, opts=opts, typ=DnsSearchPaths).value

    return AwaitableDnsSearchPaths(
        search_paths=pulumi.get(__ret__, 'search_paths'))
def list_search_paths_output(tailnet: Optional[pulumi.Input[str]] = None,
                             opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[DnsSearchPaths]:
    """
    Use this data source to access information about an existing resource.

    :param str tailnet: For paid plans, your domain is your tailnet. For solo plans, the tailnet is the email you signed up with. So `alice@gmail.com` has the tailnet `alice@gmail.com` since `@gmail.com` is a shared email host. Alternatively, you can specify the value "-" to refer to the default tailnet of the authenticated user making the API call.
    """
    __args__ = dict()
    __args__['tailnet'] = tailnet
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('tailscale-native:tailnet:listSearchPaths', __args__, opts=opts, typ=DnsSearchPaths)
    return __ret__.apply(lambda __response__: DnsSearchPaths(
        search_paths=pulumi.get(__response__, 'search_paths')))
