# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs
from ._enums import *

__all__ = [
    'AclRule',
    'AuthKey',
    'ClientConnectivity',
    'ClientSupports',
    'CreateKey',
    'Device',
    'DeviceKeyCapabilities',
    'KeyCapabilities',
    'NodeAttrs',
    'SshRule',
]

@pulumi.output_type
class AclRule(dict):
    def __init__(__self__, *,
                 action: 'AclRuleAction',
                 ports: Sequence[_builtins.str],
                 users: Sequence[_builtins.str]):
        """
        :param 'AclRuleAction' action: Tailscale ACL rules are "default deny".
               So the only possible value for an ACL
               rule is `accept`.
        """
        pulumi.set(__self__, "action", action)
        pulumi.set(__self__, "ports", ports)
        pulumi.set(__self__, "users", users)

    @_builtins.property
    @pulumi.getter
    def action(self) -> 'AclRuleAction':
        """
        Tailscale ACL rules are "default deny".
        So the only possible value for an ACL
        rule is `accept`.
        """
        return pulumi.get(self, "action")

    @_builtins.property
    @pulumi.getter
    def ports(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "ports")

    @_builtins.property
    @pulumi.getter
    def users(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "users")


@pulumi.output_type
class AuthKey(dict):
    def __init__(__self__, *,
                 expires: _builtins.str,
                 key: _builtins.str,
                 created: Optional[_builtins.str] = None):
        pulumi.set(__self__, "expires", expires)
        pulumi.set(__self__, "key", key)
        if created is not None:
            pulumi.set(__self__, "created", created)

    @_builtins.property
    @pulumi.getter
    def expires(self) -> _builtins.str:
        return pulumi.get(self, "expires")

    @_builtins.property
    @pulumi.getter
    def key(self) -> _builtins.str:
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter
    def created(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "created")


@pulumi.output_type
class ClientConnectivity(dict):
    def __init__(__self__, *,
                 client_supports: 'outputs.ClientSupports',
                 derp: _builtins.str,
                 endpoints: _builtins.str,
                 latency: Any,
                 mapping_varies_by_dest_ip: _builtins.bool):
        pulumi.set(__self__, "client_supports", client_supports)
        pulumi.set(__self__, "derp", derp)
        pulumi.set(__self__, "endpoints", endpoints)
        pulumi.set(__self__, "latency", latency)
        pulumi.set(__self__, "mapping_varies_by_dest_ip", mapping_varies_by_dest_ip)

    @_builtins.property
    @pulumi.getter(name="clientSupports")
    def client_supports(self) -> 'outputs.ClientSupports':
        return pulumi.get(self, "client_supports")

    @_builtins.property
    @pulumi.getter
    def derp(self) -> _builtins.str:
        return pulumi.get(self, "derp")

    @_builtins.property
    @pulumi.getter
    def endpoints(self) -> _builtins.str:
        return pulumi.get(self, "endpoints")

    @_builtins.property
    @pulumi.getter
    def latency(self) -> Any:
        return pulumi.get(self, "latency")

    @_builtins.property
    @pulumi.getter(name="mappingVariesByDestIP")
    def mapping_varies_by_dest_ip(self) -> _builtins.bool:
        return pulumi.get(self, "mapping_varies_by_dest_ip")


@pulumi.output_type
class ClientSupports(dict):
    def __init__(__self__, *,
                 hair_pinning: _builtins.bool,
                 ipv6: _builtins.bool,
                 pcp: _builtins.bool,
                 pmp: _builtins.bool,
                 udp: _builtins.bool,
                 upnp: _builtins.bool):
        pulumi.set(__self__, "hair_pinning", hair_pinning)
        pulumi.set(__self__, "ipv6", ipv6)
        pulumi.set(__self__, "pcp", pcp)
        pulumi.set(__self__, "pmp", pmp)
        pulumi.set(__self__, "udp", udp)
        pulumi.set(__self__, "upnp", upnp)

    @_builtins.property
    @pulumi.getter(name="hairPinning")
    def hair_pinning(self) -> _builtins.bool:
        return pulumi.get(self, "hair_pinning")

    @_builtins.property
    @pulumi.getter
    def ipv6(self) -> _builtins.bool:
        return pulumi.get(self, "ipv6")

    @_builtins.property
    @pulumi.getter
    def pcp(self) -> _builtins.bool:
        return pulumi.get(self, "pcp")

    @_builtins.property
    @pulumi.getter
    def pmp(self) -> _builtins.bool:
        return pulumi.get(self, "pmp")

    @_builtins.property
    @pulumi.getter
    def udp(self) -> _builtins.bool:
        return pulumi.get(self, "udp")

    @_builtins.property
    @pulumi.getter
    def upnp(self) -> _builtins.bool:
        return pulumi.get(self, "upnp")


@pulumi.output_type
class CreateKey(dict):
    def __init__(__self__, *,
                 ephemeral: _builtins.bool,
                 preauthorized: _builtins.bool,
                 reusable: _builtins.bool,
                 tags: Sequence[_builtins.str]):
        pulumi.set(__self__, "ephemeral", ephemeral)
        pulumi.set(__self__, "preauthorized", preauthorized)
        pulumi.set(__self__, "reusable", reusable)
        pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter
    def ephemeral(self) -> _builtins.bool:
        return pulumi.get(self, "ephemeral")

    @_builtins.property
    @pulumi.getter
    def preauthorized(self) -> _builtins.bool:
        return pulumi.get(self, "preauthorized")

    @_builtins.property
    @pulumi.getter
    def reusable(self) -> _builtins.bool:
        return pulumi.get(self, "reusable")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "tags")


@pulumi.output_type
class Device(dict):
    def __init__(__self__, *,
                 addresses: Sequence[_builtins.str],
                 advertised_routes: Sequence[_builtins.str],
                 authorized: _builtins.bool,
                 blocks_incoming_connections: _builtins.bool,
                 client_connectivity: 'outputs.ClientConnectivity',
                 client_version: _builtins.str,
                 created: _builtins.str,
                 enabled_routes: Sequence[_builtins.str],
                 expires: _builtins.str,
                 hostname: _builtins.str,
                 id: _builtins.str,
                 is_external: _builtins.bool,
                 key_expiry_disabled: _builtins.bool,
                 last_seen: _builtins.str,
                 machine_key: _builtins.str,
                 name: _builtins.str,
                 node_key: _builtins.str,
                 os: _builtins.str,
                 update_available: _builtins.bool,
                 user: _builtins.str):
        pulumi.set(__self__, "addresses", addresses)
        pulumi.set(__self__, "advertised_routes", advertised_routes)
        pulumi.set(__self__, "authorized", authorized)
        pulumi.set(__self__, "blocks_incoming_connections", blocks_incoming_connections)
        pulumi.set(__self__, "client_connectivity", client_connectivity)
        pulumi.set(__self__, "client_version", client_version)
        pulumi.set(__self__, "created", created)
        pulumi.set(__self__, "enabled_routes", enabled_routes)
        pulumi.set(__self__, "expires", expires)
        pulumi.set(__self__, "hostname", hostname)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "is_external", is_external)
        pulumi.set(__self__, "key_expiry_disabled", key_expiry_disabled)
        pulumi.set(__self__, "last_seen", last_seen)
        pulumi.set(__self__, "machine_key", machine_key)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "node_key", node_key)
        pulumi.set(__self__, "os", os)
        pulumi.set(__self__, "update_available", update_available)
        pulumi.set(__self__, "user", user)

    @_builtins.property
    @pulumi.getter
    def addresses(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "addresses")

    @_builtins.property
    @pulumi.getter(name="advertisedRoutes")
    def advertised_routes(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "advertised_routes")

    @_builtins.property
    @pulumi.getter
    def authorized(self) -> _builtins.bool:
        return pulumi.get(self, "authorized")

    @_builtins.property
    @pulumi.getter(name="blocksIncomingConnections")
    def blocks_incoming_connections(self) -> _builtins.bool:
        return pulumi.get(self, "blocks_incoming_connections")

    @_builtins.property
    @pulumi.getter(name="clientConnectivity")
    def client_connectivity(self) -> 'outputs.ClientConnectivity':
        return pulumi.get(self, "client_connectivity")

    @_builtins.property
    @pulumi.getter(name="clientVersion")
    def client_version(self) -> _builtins.str:
        return pulumi.get(self, "client_version")

    @_builtins.property
    @pulumi.getter
    def created(self) -> _builtins.str:
        return pulumi.get(self, "created")

    @_builtins.property
    @pulumi.getter(name="enabledRoutes")
    def enabled_routes(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "enabled_routes")

    @_builtins.property
    @pulumi.getter
    def expires(self) -> _builtins.str:
        return pulumi.get(self, "expires")

    @_builtins.property
    @pulumi.getter
    def hostname(self) -> _builtins.str:
        return pulumi.get(self, "hostname")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="isExternal")
    def is_external(self) -> _builtins.bool:
        return pulumi.get(self, "is_external")

    @_builtins.property
    @pulumi.getter(name="keyExpiryDisabled")
    def key_expiry_disabled(self) -> _builtins.bool:
        return pulumi.get(self, "key_expiry_disabled")

    @_builtins.property
    @pulumi.getter(name="lastSeen")
    def last_seen(self) -> _builtins.str:
        return pulumi.get(self, "last_seen")

    @_builtins.property
    @pulumi.getter(name="machineKey")
    def machine_key(self) -> _builtins.str:
        return pulumi.get(self, "machine_key")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="nodeKey")
    def node_key(self) -> _builtins.str:
        return pulumi.get(self, "node_key")

    @_builtins.property
    @pulumi.getter
    def os(self) -> _builtins.str:
        return pulumi.get(self, "os")

    @_builtins.property
    @pulumi.getter(name="updateAvailable")
    def update_available(self) -> _builtins.bool:
        return pulumi.get(self, "update_available")

    @_builtins.property
    @pulumi.getter
    def user(self) -> _builtins.str:
        return pulumi.get(self, "user")


@pulumi.output_type
class DeviceKeyCapabilities(dict):
    def __init__(__self__, *,
                 create: 'outputs.CreateKey'):
        pulumi.set(__self__, "create", create)

    @_builtins.property
    @pulumi.getter
    def create(self) -> 'outputs.CreateKey':
        return pulumi.get(self, "create")


@pulumi.output_type
class KeyCapabilities(dict):
    def __init__(__self__, *,
                 devices: 'outputs.DeviceKeyCapabilities'):
        pulumi.set(__self__, "devices", devices)

    @_builtins.property
    @pulumi.getter
    def devices(self) -> 'outputs.DeviceKeyCapabilities':
        return pulumi.get(self, "devices")


@pulumi.output_type
class NodeAttrs(dict):
    def __init__(__self__, *,
                 attr: Sequence[_builtins.str],
                 target: Sequence[_builtins.str]):
        pulumi.set(__self__, "attr", attr)
        pulumi.set(__self__, "target", target)

    @_builtins.property
    @pulumi.getter
    def attr(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "attr")

    @_builtins.property
    @pulumi.getter
    def target(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "target")


@pulumi.output_type
class SshRule(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "checkPeriod":
            suggest = "check_period"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in SshRule. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        SshRule.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        SshRule.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 action: 'SshRuleAction',
                 check_period: _builtins.str,
                 dst: Sequence[_builtins.str],
                 src: Sequence[_builtins.str],
                 users: Sequence[_builtins.str]):
        pulumi.set(__self__, "action", action)
        pulumi.set(__self__, "check_period", check_period)
        pulumi.set(__self__, "dst", dst)
        pulumi.set(__self__, "src", src)
        pulumi.set(__self__, "users", users)

    @_builtins.property
    @pulumi.getter
    def action(self) -> 'SshRuleAction':
        return pulumi.get(self, "action")

    @_builtins.property
    @pulumi.getter(name="checkPeriod")
    def check_period(self) -> _builtins.str:
        return pulumi.get(self, "check_period")

    @_builtins.property
    @pulumi.getter
    def dst(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "dst")

    @_builtins.property
    @pulumi.getter
    def src(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "src")

    @_builtins.property
    @pulumi.getter
    def users(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "users")


