# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = ['ReplaceSearchPathsArgs', 'ReplaceSearchPaths']

@pulumi.input_type
class ReplaceSearchPathsArgs:
    def __init__(__self__, *,
                 search_paths: pulumi.Input[Sequence[pulumi.Input[str]]],
                 tailnet: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a ReplaceSearchPaths resource.
        """
        pulumi.set(__self__, "search_paths", search_paths)
        if tailnet is not None:
            pulumi.set(__self__, "tailnet", tailnet)

    @property
    @pulumi.getter(name="searchPaths")
    def search_paths(self) -> pulumi.Input[Sequence[pulumi.Input[str]]]:
        return pulumi.get(self, "search_paths")

    @search_paths.setter
    def search_paths(self, value: pulumi.Input[Sequence[pulumi.Input[str]]]):
        pulumi.set(self, "search_paths", value)

    @property
    @pulumi.getter
    def tailnet(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "tailnet")

    @tailnet.setter
    def tailnet(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "tailnet", value)


class ReplaceSearchPaths(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 search_paths: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 tailnet: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Create a ReplaceSearchPaths resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ReplaceSearchPathsArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a ReplaceSearchPaths resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param ReplaceSearchPathsArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ReplaceSearchPathsArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 search_paths: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 tailnet: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ReplaceSearchPathsArgs.__new__(ReplaceSearchPathsArgs)

            if search_paths is None and not opts.urn:
                raise TypeError("Missing required property 'search_paths'")
            __props__.__dict__["search_paths"] = search_paths
            __props__.__dict__["tailnet"] = tailnet
        super(ReplaceSearchPaths, __self__).__init__(
            'tailscale-native:tailnet:replaceSearchPaths',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'ReplaceSearchPaths':
        """
        Get an existing ReplaceSearchPaths resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = ReplaceSearchPathsArgs.__new__(ReplaceSearchPathsArgs)

        __props__.__dict__["search_paths"] = None
        return ReplaceSearchPaths(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="searchPaths")
    def search_paths(self) -> pulumi.Output[Sequence[str]]:
        return pulumi.get(self, "search_paths")

