// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";

export namespace device {
}

export namespace tailnet {
    export interface AclRuleArgs {
        /**
         * Tailscale ACL rules are "default deny".
         * So the only possible value for an ACL
         * rule is `accept`.
         */
        action: pulumi.Input<enums.tailnet.AclRuleAction>;
        ports: pulumi.Input<pulumi.Input<string>[]>;
        users: pulumi.Input<pulumi.Input<string>[]>;
    }

    export interface CreateKeyArgs {
        ephemeral: pulumi.Input<boolean>;
        preauthorized: pulumi.Input<boolean>;
        reusable: pulumi.Input<boolean>;
        tags: pulumi.Input<pulumi.Input<string>[]>;
    }

    export interface DeviceKeyCapabilitiesArgs {
        create: pulumi.Input<inputs.tailnet.CreateKeyArgs>;
    }

    export interface KeyCapabilitiesArgs {
        devices: pulumi.Input<inputs.tailnet.DeviceKeyCapabilitiesArgs>;
    }

    export interface NodeAttrsArgs {
        attr: pulumi.Input<pulumi.Input<string>[]>;
        target: pulumi.Input<pulumi.Input<string>[]>;
    }

    export interface SshRuleArgs {
        action: pulumi.Input<enums.tailnet.SshRuleAction>;
        checkPeriod: pulumi.Input<string>;
        dst: pulumi.Input<pulumi.Input<string>[]>;
        src: pulumi.Input<pulumi.Input<string>[]>;
        users: pulumi.Input<pulumi.Input<string>[]>;
    }
}
