// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export function getNameServers(args: GetNameServersArgs, opts?: pulumi.InvokeOptions): Promise<GetNameServersResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tailscale-native:tailnet:getNameServers", {
        "tailnet": args.tailnet,
    }, opts);
}

export interface GetNameServersArgs {
    tailnet: string;
}

export interface GetNameServersResult {
    readonly items: outputs.tailnet.NameServers;
}
export function getNameServersOutput(args: GetNameServersOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetNameServersResult> {
    return pulumi.output(args).apply((a: any) => getNameServers(a, opts))
}

export interface GetNameServersOutputArgs {
    tailnet: pulumi.Input<string>;
}
