// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { AclArgs } from "./acl";
export type Acl = import("./acl").Acl;
export const Acl: typeof import("./acl").Acl = null as any;
utilities.lazyLoad(exports, ["Acl"], () => require("./acl"));

export { DNSPreferencesArgs } from "./dnspreferences";
export type DNSPreferences = import("./dnspreferences").DNSPreferences;
export const DNSPreferences: typeof import("./dnspreferences").DNSPreferences = null as any;
utilities.lazyLoad(exports, ["DNSPreferences"], () => require("./dnspreferences"));

export { GetAclArgs, GetAclResult, GetAclOutputArgs } from "./getAcl";
export const getAcl: typeof import("./getAcl").getAcl = null as any;
export const getAclOutput: typeof import("./getAcl").getAclOutput = null as any;
utilities.lazyLoad(exports, ["getAcl","getAclOutput"], () => require("./getAcl"));

export { GetDNSPreferenceArgs, GetDNSPreferenceResult, GetDNSPreferenceOutputArgs } from "./getDNSPreference";
export const getDNSPreference: typeof import("./getDNSPreference").getDNSPreference = null as any;
export const getDNSPreferenceOutput: typeof import("./getDNSPreference").getDNSPreferenceOutput = null as any;
utilities.lazyLoad(exports, ["getDNSPreference","getDNSPreferenceOutput"], () => require("./getDNSPreference"));

export { GetKeyArgs, GetKeyResult, GetKeyOutputArgs } from "./getKey";
export const getKey: typeof import("./getKey").getKey = null as any;
export const getKeyOutput: typeof import("./getKey").getKeyOutput = null as any;
utilities.lazyLoad(exports, ["getKey","getKeyOutput"], () => require("./getKey"));

export { GetNameServerArgs, GetNameServerResult, GetNameServerOutputArgs } from "./getNameServer";
export const getNameServer: typeof import("./getNameServer").getNameServer = null as any;
export const getNameServerOutput: typeof import("./getNameServer").getNameServerOutput = null as any;
utilities.lazyLoad(exports, ["getNameServer","getNameServerOutput"], () => require("./getNameServer"));

export { KeyArgs } from "./key";
export type Key = import("./key").Key;
export const Key: typeof import("./key").Key = null as any;
utilities.lazyLoad(exports, ["Key"], () => require("./key"));

export { ListDevicesArgs, ListDevicesResult, ListDevicesOutputArgs } from "./listDevices";
export const listDevices: typeof import("./listDevices").listDevices = null as any;
export const listDevicesOutput: typeof import("./listDevices").listDevicesOutput = null as any;
utilities.lazyLoad(exports, ["listDevices","listDevicesOutput"], () => require("./listDevices"));

export { ListKeysArgs, ListKeysResult, ListKeysOutputArgs } from "./listKeys";
export const listKeys: typeof import("./listKeys").listKeys = null as any;
export const listKeysOutput: typeof import("./listKeys").listKeysOutput = null as any;
utilities.lazyLoad(exports, ["listKeys","listKeysOutput"], () => require("./listKeys"));

export { ListSearchPathsArgs, ListSearchPathsResult, ListSearchPathsOutputArgs } from "./listSearchPaths";
export const listSearchPaths: typeof import("./listSearchPaths").listSearchPaths = null as any;
export const listSearchPathsOutput: typeof import("./listSearchPaths").listSearchPathsOutput = null as any;
utilities.lazyLoad(exports, ["listSearchPaths","listSearchPathsOutput"], () => require("./listSearchPaths"));

export { NameServersArgs } from "./nameServers";
export type NameServers = import("./nameServers").NameServers;
export const NameServers: typeof import("./nameServers").NameServers = null as any;
utilities.lazyLoad(exports, ["NameServers"], () => require("./nameServers"));

export { ReplaceSearchPathsArgs } from "./replaceSearchPaths";
export type ReplaceSearchPaths = import("./replaceSearchPaths").ReplaceSearchPaths;
export const ReplaceSearchPaths: typeof import("./replaceSearchPaths").ReplaceSearchPaths = null as any;
utilities.lazyLoad(exports, ["ReplaceSearchPaths"], () => require("./replaceSearchPaths"));


// Export enums:
export * from "../types/enums/tailnet";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "tailscale-native:tailnet:Acl":
                return new Acl(name, <any>undefined, { urn })
            case "tailscale-native:tailnet:DNSPreferences":
                return new DNSPreferences(name, <any>undefined, { urn })
            case "tailscale-native:tailnet:Key":
                return new Key(name, <any>undefined, { urn })
            case "tailscale-native:tailnet:NameServers":
                return new NameServers(name, <any>undefined, { urn })
            case "tailscale-native:tailnet:ReplaceSearchPaths":
                return new ReplaceSearchPaths(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("tailscale-native", "tailnet", _module)
