// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export function listKeys(args: ListKeysArgs, opts?: pulumi.InvokeOptions): Promise<ListKeysResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tailscale:tailnet:listKeys", {
        "tailnet": args.tailnet,
    }, opts);
}

export interface ListKeysArgs {
    tailnet: string;
}

export interface ListKeysResult {
    readonly items: outputs.tailnet.AuthKeyRead;
}
export function listKeysOutput(args: ListKeysOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<ListKeysResult> {
    return pulumi.output(args).apply((a: any) => listKeys(a, opts))
}

export interface ListKeysOutputArgs {
    tailnet: pulumi.Input<string>;
}
