// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.TailscaleNative.Tailnet.Outputs
{

    [OutputType]
    public sealed class Acl
    {
        public readonly ImmutableArray<Outputs.AclRule> Acls;
        public readonly object AutoApprovers;
        public readonly object Groups;
        public readonly object Hosts;
        public readonly ImmutableArray<Outputs.NodeAttrs> NodeAttrs;
        public readonly ImmutableArray<Outputs.SshRule> Ssh;
        public readonly object TagOwners;
        public readonly string Tests;

        [OutputConstructor]
        private Acl(
            ImmutableArray<Outputs.AclRule> acls,

            object autoApprovers,

            object groups,

            object hosts,

            ImmutableArray<Outputs.NodeAttrs> nodeAttrs,

            ImmutableArray<Outputs.SshRule> ssh,

            object tagOwners,

            string tests)
        {
            Acls = acls;
            AutoApprovers = autoApprovers;
            Groups = groups;
            Hosts = hosts;
            NodeAttrs = nodeAttrs;
            Ssh = ssh;
            TagOwners = tagOwners;
            Tests = tests;
        }
    }
}
