// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tailscale.Tailnet.Outputs
{

    [OutputType]
    public sealed class AclRule
    {
        public readonly Pulumi.Tailscale.Tailnet.AclRuleAction Action;
        public readonly ImmutableArray<string> Ports;
        public readonly ImmutableArray<string> Users;

        [OutputConstructor]
        private AclRule(
            Pulumi.Tailscale.Tailnet.AclRuleAction action,

            ImmutableArray<string> ports,

            ImmutableArray<string> users)
        {
            Action = action;
            Ports = ports;
            Users = users;
        }
    }
}
