// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tailscale.Tailnet.Outputs
{

    [OutputType]
    public sealed class AuthKeyRead
    {
        public readonly string? Created;
        public readonly string Expires;
        public readonly string Id;
        public readonly string Key;

        [OutputConstructor]
        private AuthKeyRead(
            string? created,

            string expires,

            string id,

            string key)
        {
            Created = created;
            Expires = expires;
            Id = id;
            Key = key;
        }
    }
}
