// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.TailscaleNative.Tailnet.Outputs
{

    [OutputType]
    public sealed class ClientConnectivity
    {
        public readonly Outputs.ClientSupports ClientSupports;
        public readonly string Derp;
        public readonly string Endpoints;
        public readonly object Latency;
        public readonly bool MappingVariesByDestIP;

        [OutputConstructor]
        private ClientConnectivity(
            Outputs.ClientSupports clientSupports,

            string derp,

            string endpoints,

            object latency,

            bool mappingVariesByDestIP)
        {
            ClientSupports = clientSupports;
            Derp = derp;
            Endpoints = endpoints;
            Latency = latency;
            MappingVariesByDestIP = mappingVariesByDestIP;
        }
    }
}
