// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tailscale.Tailnet.Outputs
{

    [OutputType]
    public sealed class CreateKey
    {
        public readonly bool Ephemeral;
        public readonly bool Preauthorized;
        public readonly bool Reusable;
        public readonly ImmutableArray<string> Tags;

        [OutputConstructor]
        private CreateKey(
            bool ephemeral,

            bool preauthorized,

            bool reusable,

            ImmutableArray<string> tags)
        {
            Ephemeral = ephemeral;
            Preauthorized = preauthorized;
            Reusable = reusable;
            Tags = tags;
        }
    }
}
