// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.TailscaleNative.Tailnet.Outputs
{

    [OutputType]
    public sealed class DeviceKeyCapabilities
    {
        public readonly Outputs.CreateKey Create;

        [OutputConstructor]
        private DeviceKeyCapabilities(Outputs.CreateKey create)
        {
            Create = create;
        }
    }
}
