// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tailscale.Tailnet.Outputs
{

    [OutputType]
    public sealed class NodeAttrs
    {
        public readonly ImmutableArray<string> Attr;
        public readonly ImmutableArray<string> Target;

        [OutputConstructor]
        private NodeAttrs(
            ImmutableArray<string> attr,

            ImmutableArray<string> target)
        {
            Attr = attr;
            Target = target;
        }
    }
}
