// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package device

import (
	"fmt"

	"github.com/blang/semver"
	tailscale "github.com/cloudy-sky-software/pulumi-tailscale-native/sdk/go/tailscale"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "tailscale-native:device:KeyExpiry":
		r = &KeyExpiry{}
	case "tailscale-native:device:Routes":
		r = &Routes{}
	case "tailscale-native:device:Tags":
		r = &Tags{}
	case "tailscale-native:device:authorizeDevice":
		r = &AuthorizeDevice{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := tailscale.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"tailscale-native",
		"device",
		&module{version},
	)
}
