// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package device

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-tailscale-native/sdk/go/tailscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type ClientConnectivity struct {
	ClientSupports        ClientSupports `pulumi:"clientSupports"`
	Derp                  string         `pulumi:"derp"`
	Endpoints             string         `pulumi:"endpoints"`
	Latency               interface{}    `pulumi:"latency"`
	MappingVariesByDestIP bool           `pulumi:"mappingVariesByDestIP"`
}

type ClientConnectivityOutput struct{ *pulumi.OutputState }

func (ClientConnectivityOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ClientConnectivity)(nil)).Elem()
}

func (o ClientConnectivityOutput) ToClientConnectivityOutput() ClientConnectivityOutput {
	return o
}

func (o ClientConnectivityOutput) ToClientConnectivityOutputWithContext(ctx context.Context) ClientConnectivityOutput {
	return o
}

func (o ClientConnectivityOutput) ClientSupports() ClientSupportsOutput {
	return o.ApplyT(func(v ClientConnectivity) ClientSupports { return v.ClientSupports }).(ClientSupportsOutput)
}

func (o ClientConnectivityOutput) Derp() pulumi.StringOutput {
	return o.ApplyT(func(v ClientConnectivity) string { return v.Derp }).(pulumi.StringOutput)
}

func (o ClientConnectivityOutput) Endpoints() pulumi.StringOutput {
	return o.ApplyT(func(v ClientConnectivity) string { return v.Endpoints }).(pulumi.StringOutput)
}

func (o ClientConnectivityOutput) Latency() pulumi.AnyOutput {
	return o.ApplyT(func(v ClientConnectivity) interface{} { return v.Latency }).(pulumi.AnyOutput)
}

func (o ClientConnectivityOutput) MappingVariesByDestIP() pulumi.BoolOutput {
	return o.ApplyT(func(v ClientConnectivity) bool { return v.MappingVariesByDestIP }).(pulumi.BoolOutput)
}

type ClientSupports struct {
	HairPinning bool `pulumi:"hairPinning"`
	Ipv6        bool `pulumi:"ipv6"`
	Pcp         bool `pulumi:"pcp"`
	Pmp         bool `pulumi:"pmp"`
	Udp         bool `pulumi:"udp"`
	Upnp        bool `pulumi:"upnp"`
}

type ClientSupportsOutput struct{ *pulumi.OutputState }

func (ClientSupportsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ClientSupports)(nil)).Elem()
}

func (o ClientSupportsOutput) ToClientSupportsOutput() ClientSupportsOutput {
	return o
}

func (o ClientSupportsOutput) ToClientSupportsOutputWithContext(ctx context.Context) ClientSupportsOutput {
	return o
}

func (o ClientSupportsOutput) HairPinning() pulumi.BoolOutput {
	return o.ApplyT(func(v ClientSupports) bool { return v.HairPinning }).(pulumi.BoolOutput)
}

func (o ClientSupportsOutput) Ipv6() pulumi.BoolOutput {
	return o.ApplyT(func(v ClientSupports) bool { return v.Ipv6 }).(pulumi.BoolOutput)
}

func (o ClientSupportsOutput) Pcp() pulumi.BoolOutput {
	return o.ApplyT(func(v ClientSupports) bool { return v.Pcp }).(pulumi.BoolOutput)
}

func (o ClientSupportsOutput) Pmp() pulumi.BoolOutput {
	return o.ApplyT(func(v ClientSupports) bool { return v.Pmp }).(pulumi.BoolOutput)
}

func (o ClientSupportsOutput) Udp() pulumi.BoolOutput {
	return o.ApplyT(func(v ClientSupports) bool { return v.Udp }).(pulumi.BoolOutput)
}

func (o ClientSupportsOutput) Upnp() pulumi.BoolOutput {
	return o.ApplyT(func(v ClientSupports) bool { return v.Upnp }).(pulumi.BoolOutput)
}

type Device struct {
	Addresses                 []string           `pulumi:"addresses"`
	AdvertisedRoutes          []string           `pulumi:"advertisedRoutes"`
	Authorized                bool               `pulumi:"authorized"`
	BlocksIncomingConnections bool               `pulumi:"blocksIncomingConnections"`
	ClientConnectivity        ClientConnectivity `pulumi:"clientConnectivity"`
	ClientVersion             string             `pulumi:"clientVersion"`
	Created                   string             `pulumi:"created"`
	EnabledRoutes             []string           `pulumi:"enabledRoutes"`
	Expires                   string             `pulumi:"expires"`
	Hostname                  string             `pulumi:"hostname"`
	Id                        string             `pulumi:"id"`
	IsExternal                bool               `pulumi:"isExternal"`
	KeyExpiryDisabled         bool               `pulumi:"keyExpiryDisabled"`
	LastSeen                  string             `pulumi:"lastSeen"`
	MachineKey                string             `pulumi:"machineKey"`
	Name                      string             `pulumi:"name"`
	NodeKey                   string             `pulumi:"nodeKey"`
	Os                        string             `pulumi:"os"`
	UpdateAvailable           bool               `pulumi:"updateAvailable"`
	User                      string             `pulumi:"user"`
}

type DeviceRoutes struct {
	AdvertisedRoutes []string `pulumi:"advertisedRoutes"`
	EnabledRoutes    []string `pulumi:"enabledRoutes"`
}

func init() {
	pulumi.RegisterOutputType(ClientConnectivityOutput{})
	pulumi.RegisterOutputType(ClientSupportsOutput{})
}
