// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package tailnet

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type TailnetEndpoints_replaceSearchPaths struct {
	pulumi.CustomResourceState

	SearchPaths pulumi.StringArrayOutput `pulumi:"searchPaths"`
}

// NewTailnetEndpoints_replaceSearchPaths registers a new resource with the given unique name, arguments, and options.
func NewTailnetEndpoints_replaceSearchPaths(ctx *pulumi.Context,
	name string, args *TailnetEndpoints_replaceSearchPathsArgs, opts ...pulumi.ResourceOption) (*TailnetEndpoints_replaceSearchPaths, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.SearchPaths == nil {
		return nil, errors.New("invalid value for required argument 'SearchPaths'")
	}
	opts = pkgResourceDefaultOpts(opts)
	var resource TailnetEndpoints_replaceSearchPaths
	err := ctx.RegisterResource("tailscale:tailnet:TailnetEndpoints_replaceSearchPaths", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetTailnetEndpoints_replaceSearchPaths gets an existing TailnetEndpoints_replaceSearchPaths resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetTailnetEndpoints_replaceSearchPaths(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *TailnetEndpoints_replaceSearchPathsState, opts ...pulumi.ResourceOption) (*TailnetEndpoints_replaceSearchPaths, error) {
	var resource TailnetEndpoints_replaceSearchPaths
	err := ctx.ReadResource("tailscale:tailnet:TailnetEndpoints_replaceSearchPaths", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering TailnetEndpoints_replaceSearchPaths resources.
type tailnetEndpoints_replaceSearchPathsState struct {
}

type TailnetEndpoints_replaceSearchPathsState struct {
}

func (TailnetEndpoints_replaceSearchPathsState) ElementType() reflect.Type {
	return reflect.TypeOf((*tailnetEndpoints_replaceSearchPathsState)(nil)).Elem()
}

type tailnetEndpoints_replaceSearchPathsArgs struct {
	SearchPaths []string `pulumi:"searchPaths"`
	Tailnet     *string  `pulumi:"tailnet"`
}

// The set of arguments for constructing a TailnetEndpoints_replaceSearchPaths resource.
type TailnetEndpoints_replaceSearchPathsArgs struct {
	SearchPaths pulumi.StringArrayInput
	Tailnet     pulumi.StringPtrInput
}

func (TailnetEndpoints_replaceSearchPathsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*tailnetEndpoints_replaceSearchPathsArgs)(nil)).Elem()
}

type TailnetEndpoints_replaceSearchPathsInput interface {
	pulumi.Input

	ToTailnetEndpoints_replaceSearchPathsOutput() TailnetEndpoints_replaceSearchPathsOutput
	ToTailnetEndpoints_replaceSearchPathsOutputWithContext(ctx context.Context) TailnetEndpoints_replaceSearchPathsOutput
}

func (*TailnetEndpoints_replaceSearchPaths) ElementType() reflect.Type {
	return reflect.TypeOf((**TailnetEndpoints_replaceSearchPaths)(nil)).Elem()
}

func (i *TailnetEndpoints_replaceSearchPaths) ToTailnetEndpoints_replaceSearchPathsOutput() TailnetEndpoints_replaceSearchPathsOutput {
	return i.ToTailnetEndpoints_replaceSearchPathsOutputWithContext(context.Background())
}

func (i *TailnetEndpoints_replaceSearchPaths) ToTailnetEndpoints_replaceSearchPathsOutputWithContext(ctx context.Context) TailnetEndpoints_replaceSearchPathsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TailnetEndpoints_replaceSearchPathsOutput)
}

type TailnetEndpoints_replaceSearchPathsOutput struct{ *pulumi.OutputState }

func (TailnetEndpoints_replaceSearchPathsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**TailnetEndpoints_replaceSearchPaths)(nil)).Elem()
}

func (o TailnetEndpoints_replaceSearchPathsOutput) ToTailnetEndpoints_replaceSearchPathsOutput() TailnetEndpoints_replaceSearchPathsOutput {
	return o
}

func (o TailnetEndpoints_replaceSearchPathsOutput) ToTailnetEndpoints_replaceSearchPathsOutputWithContext(ctx context.Context) TailnetEndpoints_replaceSearchPathsOutput {
	return o
}

func (o TailnetEndpoints_replaceSearchPathsOutput) SearchPaths() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *TailnetEndpoints_replaceSearchPaths) pulumi.StringArrayOutput { return v.SearchPaths }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TailnetEndpoints_replaceSearchPathsInput)(nil)).Elem(), &TailnetEndpoints_replaceSearchPaths{})
	pulumi.RegisterOutputType(TailnetEndpoints_replaceSearchPathsOutput{})
}
