// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tailscale.Device.Outputs
{

    [OutputType]
    public sealed class DeviceRoutes
    {
        public readonly ImmutableArray<string> AdvertisedRoutes;
        public readonly ImmutableArray<string> EnabledRoutes;

        [OutputConstructor]
        private DeviceRoutes(
            ImmutableArray<string> advertisedRoutes,

            ImmutableArray<string> enabledRoutes)
        {
            AdvertisedRoutes = advertisedRoutes;
            EnabledRoutes = enabledRoutes;
        }
    }
}
