// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tailscale.Tailnet.Inputs
{

    public sealed class CreateKeyArgs : global::Pulumi.ResourceArgs
    {
        [Input("ephemeral", required: true)]
        public Input<bool> Ephemeral { get; set; } = null!;

        [Input("preauthorized", required: true)]
        public Input<bool> Preauthorized { get; set; } = null!;

        [Input("reusable", required: true)]
        public Input<bool> Reusable { get; set; } = null!;

        [Input("tags", required: true)]
        private InputList<string>? _tags;
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        public CreateKeyArgs()
        {
        }
        public static new CreateKeyArgs Empty => new CreateKeyArgs();
    }
}
