// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tailscale.Tailnet.Inputs
{

    public sealed class KeyCapabilitiesArgs : global::Pulumi.ResourceArgs
    {
        [Input("devices", required: true)]
        public Input<Inputs.DeviceKeyCapabilitiesArgs> Devices { get; set; } = null!;

        public KeyCapabilitiesArgs()
        {
        }
        public static new KeyCapabilitiesArgs Empty => new KeyCapabilitiesArgs();
    }
}
