// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.TailscaleNative.Tailnet.Inputs
{

    public sealed class SshRuleArgs : global::Pulumi.ResourceArgs
    {
        [Input("action", required: true)]
        public Input<Pulumi.TailscaleNative.Tailnet.SshRuleAction> Action { get; set; } = null!;

        [Input("checkPeriod", required: true)]
        public Input<string> CheckPeriod { get; set; } = null!;

        [Input("dst", required: true)]
        private InputList<string>? _dst;
        public InputList<string> Dst
        {
            get => _dst ?? (_dst = new InputList<string>());
            set => _dst = value;
        }

        [Input("src", required: true)]
        private InputList<string>? _src;
        public InputList<string> Src
        {
            get => _src ?? (_src = new InputList<string>());
            set => _src = value;
        }

        [Input("users", required: true)]
        private InputList<string>? _users;
        public InputList<string> Users
        {
            get => _users ?? (_users = new InputList<string>());
            set => _users = value;
        }

        public SshRuleArgs()
        {
        }
        public static new SshRuleArgs Empty => new SshRuleArgs();
    }
}
