// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { AuthorizeDeviceArgs } from "./authorizeDevice";
export type AuthorizeDevice = import("./authorizeDevice").AuthorizeDevice;
export const AuthorizeDevice: typeof import("./authorizeDevice").AuthorizeDevice = null as any;
utilities.lazyLoad(exports, ["AuthorizeDevice"], () => require("./authorizeDevice"));

export { GetDeviceArgs, GetDeviceResult, GetDeviceOutputArgs } from "./getDevice";
export const getDevice: typeof import("./getDevice").getDevice = null as any;
export const getDeviceOutput: typeof import("./getDevice").getDeviceOutput = null as any;
utilities.lazyLoad(exports, ["getDevice","getDeviceOutput"], () => require("./getDevice"));

export { GetRoutesConfigArgs, GetRoutesConfigResult, GetRoutesConfigOutputArgs } from "./getRoutesConfig";
export const getRoutesConfig: typeof import("./getRoutesConfig").getRoutesConfig = null as any;
export const getRoutesConfigOutput: typeof import("./getRoutesConfig").getRoutesConfigOutput = null as any;
utilities.lazyLoad(exports, ["getRoutesConfig","getRoutesConfigOutput"], () => require("./getRoutesConfig"));

export { KeyExpiryArgs } from "./keyExpiry";
export type KeyExpiry = import("./keyExpiry").KeyExpiry;
export const KeyExpiry: typeof import("./keyExpiry").KeyExpiry = null as any;
utilities.lazyLoad(exports, ["KeyExpiry"], () => require("./keyExpiry"));

export { RoutesConfigArgs } from "./routesConfig";
export type RoutesConfig = import("./routesConfig").RoutesConfig;
export const RoutesConfig: typeof import("./routesConfig").RoutesConfig = null as any;
utilities.lazyLoad(exports, ["RoutesConfig"], () => require("./routesConfig"));

export { TagsArgs } from "./tags";
export type Tags = import("./tags").Tags;
export const Tags: typeof import("./tags").Tags = null as any;
utilities.lazyLoad(exports, ["Tags"], () => require("./tags"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "tailscale-native:device:AuthorizeDevice":
                return new AuthorizeDevice(name, <any>undefined, { urn })
            case "tailscale-native:device:KeyExpiry":
                return new KeyExpiry(name, <any>undefined, { urn })
            case "tailscale-native:device:RoutesConfig":
                return new RoutesConfig(name, <any>undefined, { urn })
            case "tailscale-native:device:Tags":
                return new Tags(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("tailscale-native", "device", _module)
