openapi: 3.0.0
components:
    schemas:
        Acl:
            type: object
            required:
                - acls
                - autoApprovers
                - groups
                - hosts
                - nodeAttrs
                - ssh
                - tagOwners
                - tests
            properties:
                acls:
                    type: array
                    items:
                        $ref: '#/components/schemas/AclRule'
                autoApprovers:
                    type: object
                    additionalProperties:
                        has: null
                        schema:
                            type: array
                            items:
                                type: string
                groups:
                    type: object
                    additionalProperties:
                        has: null
                        schema:
                            type: array
                            items:
                                type: string
                hosts:
                    type: object
                    additionalProperties:
                        has: null
                        schema:
                            type: string
                nodeAttrs:
                    type: array
                    items:
                        $ref: '#/components/schemas/NodeAttrs'
                ssh:
                    type: array
                    items:
                        $ref: '#/components/schemas/SshRule'
                tagOwners:
                    type: object
                    additionalProperties:
                        has: null
                        schema:
                            type: array
                            items:
                                type: string
                tests:
                    type: string
        AclRule:
            type: object
            required:
                - action
                - ports
                - users
            properties:
                action:
                    $ref: '#/components/schemas/AclRuleAction'
                ports:
                    type: array
                    items:
                        type: string
                users:
                    type: array
                    items:
                        type: string
        AclRuleAction:
            type: string
            description: |-
                Tailscale ACL rules are "default deny".
                So the only possible value for an ACL
                rule is `accept`.
            enum:
                - accept
        AuthKey:
            type: object
            required:
                - key
                - expires
            properties:
                created:
                    type: string
                    readOnly: true
                expires:
                    type: string
                    readOnly: true
                key:
                    type: string
                    readOnly: true
        AuthKeyCreate:
            type: object
            required:
                - capabilities
                - expirySeconds
            properties:
                capabilities:
                    $ref: '#/components/schemas/KeyCapabilities'
                expirySeconds:
                    type: integer
                    format: int64
        ClientConnectivity:
            type: object
            required:
                - endpoints
                - derp
                - mappingVariesByDestIP
                - latency
                - clientSupports
            properties:
                clientSupports:
                    $ref: '#/components/schemas/ClientSupports'
                derp:
                    type: string
                endpoints:
                    type: string
                latency:
                    type: object
                    additionalProperties:
                        has: null
                        schema:
                            $ref: '#/components/schemas/Latency'
                mappingVariesByDestIP:
                    type: boolean
        ClientSupports:
            type: object
            required:
                - hairPinning
                - ipv6
                - pcp
                - pmp
                - udp
                - upnp
            properties:
                hairPinning:
                    type: boolean
                ipv6:
                    type: boolean
                pcp:
                    type: boolean
                pmp:
                    type: boolean
                udp:
                    type: boolean
                upnp:
                    type: boolean
        CreateKey:
            type: object
            required:
                - reusable
                - ephemeral
                - preauthorized
                - tags
            properties:
                ephemeral:
                    type: boolean
                preauthorized:
                    type: boolean
                reusable:
                    type: boolean
                tags:
                    type: array
                    items:
                        type: string
        Device:
            type: object
            required:
                - addresses
                - id
                - user
                - name
                - hostname
                - clientVersion
                - updateAvailable
                - os
                - created
                - lastSeen
                - keyExpiryDisabled
                - expires
                - authorized
                - isExternal
                - machineKey
                - nodeKey
                - blocksIncomingConnections
                - enabledRoutes
                - advertisedRoutes
                - clientConnectivity
            properties:
                addresses:
                    type: array
                    items:
                        type: string
                advertisedRoutes:
                    type: array
                    items:
                        type: string
                authorized:
                    type: boolean
                blocksIncomingConnections:
                    type: boolean
                clientConnectivity:
                    $ref: '#/components/schemas/ClientConnectivity'
                clientVersion:
                    type: string
                created:
                    type: string
                enabledRoutes:
                    type: array
                    items:
                        type: string
                expires:
                    type: string
                hostname:
                    type: string
                id:
                    type: string
                isExternal:
                    type: boolean
                keyExpiryDisabled:
                    type: boolean
                lastSeen:
                    type: string
                machineKey:
                    type: string
                name:
                    type: string
                nodeKey:
                    type: string
                os:
                    type: string
                updateAvailable:
                    type: boolean
                user:
                    type: string
        DeviceKeyCapabilities:
            type: object
            required:
                - create
            properties:
                create:
                    $ref: '#/components/schemas/CreateKey'
        DeviceRoutes:
            type: object
            required:
                - advertisedRoutes
                - enabledRoutes
            properties:
                advertisedRoutes:
                    type: array
                    items:
                        type: string
                enabledRoutes:
                    type: array
                    items:
                        type: string
        DnsSearchPaths:
            type: object
            required:
                - searchPaths
            properties:
                searchPaths:
                    type: array
                    items:
                        type: string
        Error:
            type: object
            required:
                - message
            properties:
                message:
                    type: string
        KeyCapabilities:
            type: object
            required:
                - devices
            properties:
                devices:
                    $ref: '#/components/schemas/DeviceKeyCapabilities'
        Latency:
            type: object
            required:
                - latencyMs
                - preferred
            properties:
                latencyMs:
                    type: number
                preferred:
                    type: boolean
        NameServers:
            type: object
            required:
                - dns
                - magicDNS
            properties:
                dns:
                    type: array
                    items:
                        type: string
                magicDNS:
                    type: boolean
        NameServersPreference:
            type: object
            required:
                - magicDNS
            properties:
                magicDNS:
                    type: boolean
        NodeAttrs:
            type: object
            required:
                - target
                - attr
            properties:
                attr:
                    type: array
                    items:
                        type: string
                target:
                    type: array
                    items:
                        type: string
        SetAuthorized:
            type: object
            required:
                - authorized
            properties:
                authorized:
                    type: boolean
        SetDeviceRoutes:
            type: object
            required:
                - routes
            properties:
                routes:
                    type: array
                    items:
                        type: string
        SetKeyExpiry:
            type: object
            required:
                - keyExpiryDisabled
            properties:
                keyExpiryDisabled:
                    type: boolean
        SetTags:
            type: object
            required:
                - tags
            properties:
                tags:
                    type: array
                    items:
                        type: string
        SshRule:
            type: object
            required:
                - action
                - src
                - dst
                - users
                - checkPeriod
            properties:
                action:
                    $ref: '#/components/schemas/SshRuleAction'
                checkPeriod:
                    type: string
                dst:
                    type: array
                    items:
                        type: string
                src:
                    type: array
                    items:
                        type: string
                users:
                    type: array
                    items:
                        type: string
        SshRuleAction:
            type: string
            enum:
                - check
                - accept
    parameters:
        TailnetEndpoints.CommonParameters:
            name: tailnet
            in: path
            description: For paid plans, your domain is your tailnet. For solo plans, the tailnet is the email you signed up with. So `alice@gmail.com` has the tailnet `alice@gmail.com` since `@gmail.com` is a shared email host. Alternatively, you can specify the value "-" to refer to the default tailnet of the authenticated user making the API call.
            required: true
            schema:
                anyOf:
                    - type: string
                      enum:
                        - '-'
                    - type: string
    securitySchemes:
        BasicAuth:
            type: http
            scheme: basic
        OAuth2Auth:
            type: oauth2
            flows:
                clientCredentials:
                    tokenUrl: https://api.tailscale.com/api/v2/oauth/token
                    scopes:
                        acl: ""
                        acl:read: ""
                        all: ""
                        all:read: ""
                        devices: ""
                        devices:read: ""
                        dns: ""
                        dns:read: ""
                        routes: ""
                        routes:read: ""
info:
    title: Tailscale API
    description: This namespace contains operations that can be performed on a Tailscale-connected device.
    version: "2023-01-01T00:00:00Z"
paths: {}
security:
    - BasicAuth: []
    - OAuth2Auth:
        - all
        - all:read
        - acl
        - acl:read
        - devices
        - devices:read
        - dns
        - dns:read
        - routes
        - routes:read
servers:
    - url: https://api.tailscale.com/api/v2
      description: Tailscale API
